{% set name = "dagster_aws" %}
{% set version = "0.6.7.post0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name|replace('_', '-') }}/{{ name|replace('_', '-') }}-{{ version }}.tar.gz"
  sha256: 36f20b66af0bffad7f9cb5877178a6be11770d1af870552778011512f0da7db9

build:
  number: 0
  noarch: python
  entry_points:
    - dagster-aws = dagster_aws.cli.cli:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - boto3 1.9.*
    - dagster {{ version }}.*
    - python
    - requests
    - terminaltables

test:
  requires:
    - dagster_pyspark
    - python <3.8.0a0
  imports:
    - dagster_aws
    - dagster_aws.cli
    - dagster_aws.cloudwatch
    - dagster_aws.emr
    - dagster_aws.s3
  commands:
    - dagster-aws --help

about:
  home: "https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-aws"
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "Package for AWS-specific Dagster framework solid and resource components."

extra:
  recipe-maintainers:
    - conda-forge/dagster
